add debug logs to bash code inside slackmessage

diff --git a/.github/workflows/e2e-tests.yaml b/.github/workflows/e2e-tests.yaml
--- a/.github/workflows/e2e-tests.yaml
+++ b/.github/workflows/e2e-tests.yaml
@@ -31,108 +31,108 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-      - name: Run e2e test
-        id: run_e2e_test
-        uses: ./.github/actions/run-e2e
-        with:
-          flc-namespace: dto-daily
-          flc-environment: dto-k8s-latest-flc
-          helm-chart: ${{ github.event.inputs.helm-chart || 'oci://quay.io/dynatrace/dynatrace-operator:0.0.0-nightly-chart' }}
-          target-branch: ${{ github.event.inputs.target }}
-          tenant1-name: ${{ secrets.TENANT1_NAME }}
-          tenant1-apitoken: ${{ secrets.TENANT1_APITOKEN }}
-          tenant1-apitoken-nosettings: ${{ secrets.TENANT1_APITOKEN_NOSETTINGS }}
-          tenant1-dataingesttoken: ${{ secrets.TENANT1_DATAINGESTTOKEN }}
-          tenant1-oauth-client-id: ${{ secrets.TENANT1_OAUTH_CLIENT_ID }}
-          tenant1-oauth-secret: ${{ secrets.TENANT1_OAUTH_SECRET }}
-          tenant1-oauth-urn: ${{ secrets.TENANT1_OAUTH_URN }}
-          tenant2-name: ${{ secrets.TENANT2_NAME }}
-          tenant2-apitoken: ${{ secrets.TENANT2_APITOKEN }}
-          tenant2-dataingesttoken: ${{ secrets.TENANT2_DATAINGESTTOKEN }}
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-      - name: Determine cluster status
-        if: failure()
-        run: |
-          if [[ "${{ steps.run_e2e_test.outputs.cluster_status }}" == "skipped" ]]; then
-            exit 1
-          fi
-  run-in-ocp:
-    name: Run in OpenShift latest (${{ github.event.inputs.target || 'main' }})
-    environment: E2E
-    runs-on:
-      - self-hosted
-      - operator-e2e
-    outputs:
-      cluster_status: ${{ steps.run_e2e_test.outputs.cluster_status }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-      - name: Run e2e test
-        id: run_e2e_test
-        uses: ./.github/actions/run-e2e
-        with:
-          flc-namespace: dto-daily
-          flc-environment: dto-ocp-latest-flc
-          helm-chart: ${{ github.event.inputs.helm-chart || 'oci://quay.io/dynatrace/dynatrace-operator:0.0.0-nightly-chart' }}
-          target-branch: ${{ github.event.inputs.target }}
-          tenant1-name: ${{ secrets.TENANT1_NAME }}
-          tenant1-apitoken: ${{ secrets.TENANT1_APITOKEN }}
-          tenant1-apitoken-nosettings: ${{ secrets.TENANT1_APITOKEN_NOSETTINGS }}
-          tenant1-dataingesttoken: ${{ secrets.TENANT1_DATAINGESTTOKEN }}
-          tenant1-oauth-client-id: ${{ secrets.TENANT1_OAUTH_CLIENT_ID }}
-          tenant1-oauth-secret: ${{ secrets.TENANT1_OAUTH_SECRET }}
-          tenant1-oauth-urn: ${{ secrets.TENANT1_OAUTH_URN }}
-          tenant2-name: ${{ secrets.TENANT2_NAME }}
-          tenant2-apitoken: ${{ secrets.TENANT2_APITOKEN }}
-          tenant2-dataingesttoken: ${{ secrets.TENANT2_DATAINGESTTOKEN }}
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-      - name: Determine cluster status
-        if: failure()
-        run: |
-          if [[ "${{ steps.run_e2e_test.outputs.cluster_status }}" == "skipped" ]]; then
-            exit 1
-          fi
-  run-in-ocp-fips:
-    name: Run in FIPS OpenShift (${{ github.event.inputs.target || 'main' }})
-    environment: E2E
-    runs-on:
-      - self-hosted
-      - operator-e2e
-    outputs:
-      cluster_status: ${{ steps.run_e2e_test.outputs.cluster_status }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-      - name: Run e2e test
-        id: run_e2e_test
-        uses: ./.github/actions/run-e2e
-        with:
-          flc-namespace: dto-ocp-ondemand
-          flc-environment: dto-ocp-fips
-          helm-chart: ${{ github.event.inputs.helm-chart || 'oci://quay.io/dynatrace/dynatrace-operator:0.0.0-nightly-chart' }}
-          target-image: format('{0}-fips', (${{ github.event.inputs.target || 'main' }}))
-          tenant1-name: ${{ secrets.TENANT1_NAME }}
-          tenant1-apitoken: ${{ secrets.TENANT1_APITOKEN }}
-          tenant1-apitoken-nosettings: ${{ secrets.TENANT1_APITOKEN_NOSETTINGS }}
-          tenant1-dataingesttoken: ${{ secrets.TENANT1_DATAINGESTTOKEN }}
-          tenant1-oauth-client-id: ${{ secrets.TENANT1_OAUTH_CLIENT_ID }}
-          tenant1-oauth-secret: ${{ secrets.TENANT1_OAUTH_SECRET }}
-          tenant1-oauth-urn: ${{ secrets.TENANT1_OAUTH_URN }}
-          tenant2-name: ${{ secrets.TENANT2_NAME }}
-          tenant2-apitoken: ${{ secrets.TENANT2_APITOKEN }}
-          tenant2-dataingesttoken: ${{ secrets.TENANT2_DATAINGESTTOKEN }}
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-      - name: Determine cluster status
-        if: failure()
-        run: |
-          if [[ "${{ steps.run_e2e_test.outputs.cluster_status }}" == "skipped" ]]; then
-            exit 1
-          fi
+#      - name: Run e2e test
+#        id: run_e2e_test
+#        uses: ./.github/actions/run-e2e
+#        with:
+#          flc-namespace: dto-daily
+#          flc-environment: dto-k8s-latest-flc
+#          helm-chart: ${{ github.event.inputs.helm-chart || 'oci://quay.io/dynatrace/dynatrace-operator:0.0.0-nightly-chart' }}
+#          target-branch: ${{ github.event.inputs.target }}
+#          tenant1-name: ${{ secrets.TENANT1_NAME }}
+#          tenant1-apitoken: ${{ secrets.TENANT1_APITOKEN }}
+#          tenant1-apitoken-nosettings: ${{ secrets.TENANT1_APITOKEN_NOSETTINGS }}
+#          tenant1-dataingesttoken: ${{ secrets.TENANT1_DATAINGESTTOKEN }}
+#          tenant1-oauth-client-id: ${{ secrets.TENANT1_OAUTH_CLIENT_ID }}
+#          tenant1-oauth-secret: ${{ secrets.TENANT1_OAUTH_SECRET }}
+#          tenant1-oauth-urn: ${{ secrets.TENANT1_OAUTH_URN }}
+#          tenant2-name: ${{ secrets.TENANT2_NAME }}
+#          tenant2-apitoken: ${{ secrets.TENANT2_APITOKEN }}
+#          tenant2-dataingesttoken: ${{ secrets.TENANT2_DATAINGESTTOKEN }}
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#      - name: Determine cluster status
+#        if: failure()
+#        run: |
+#          if [[ "${{ steps.run_e2e_test.outputs.cluster_status }}" == "skipped" ]]; then
+#            exit 1
+#          fi
+#  run-in-ocp:
+#    name: Run in OpenShift latest (${{ github.event.inputs.target || 'main' }})
+#    environment: E2E
+#    runs-on:
+#      - self-hosted
+#      - operator-e2e
+#    outputs:
+#      cluster_status: ${{ steps.run_e2e_test.outputs.cluster_status }}
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+#      - name: Run e2e test
+#        id: run_e2e_test
+#        uses: ./.github/actions/run-e2e
+#        with:
+#          flc-namespace: dto-daily
+#          flc-environment: dto-ocp-latest-flc
+#          helm-chart: ${{ github.event.inputs.helm-chart || 'oci://quay.io/dynatrace/dynatrace-operator:0.0.0-nightly-chart' }}
+#          target-branch: ${{ github.event.inputs.target }}
+#          tenant1-name: ${{ secrets.TENANT1_NAME }}
+#          tenant1-apitoken: ${{ secrets.TENANT1_APITOKEN }}
+#          tenant1-apitoken-nosettings: ${{ secrets.TENANT1_APITOKEN_NOSETTINGS }}
+#          tenant1-dataingesttoken: ${{ secrets.TENANT1_DATAINGESTTOKEN }}
+#          tenant1-oauth-client-id: ${{ secrets.TENANT1_OAUTH_CLIENT_ID }}
+#          tenant1-oauth-secret: ${{ secrets.TENANT1_OAUTH_SECRET }}
+#          tenant1-oauth-urn: ${{ secrets.TENANT1_OAUTH_URN }}
+#          tenant2-name: ${{ secrets.TENANT2_NAME }}
+#          tenant2-apitoken: ${{ secrets.TENANT2_APITOKEN }}
+#          tenant2-dataingesttoken: ${{ secrets.TENANT2_DATAINGESTTOKEN }}
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#      - name: Determine cluster status
+#        if: failure()
+#        run: |
+#          if [[ "${{ steps.run_e2e_test.outputs.cluster_status }}" == "skipped" ]]; then
+#            exit 1
+#          fi
+#  run-in-ocp-fips:
+#    name: Run in FIPS OpenShift (${{ github.event.inputs.target || 'main' }})
+#    environment: E2E
+#    runs-on:
+#      - self-hosted
+#      - operator-e2e
+#    outputs:
+#      cluster_status: ${{ steps.run_e2e_test.outputs.cluster_status }}
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+#      - name: Run e2e test
+#        id: run_e2e_test
+#        uses: ./.github/actions/run-e2e
+#        with:
+#          flc-namespace: dto-ocp-ondemand
+#          flc-environment: dto-ocp-fips
+#          helm-chart: ${{ github.event.inputs.helm-chart || 'oci://quay.io/dynatrace/dynatrace-operator:0.0.0-nightly-chart' }}
+#          target-image: format('{0}-fips', (${{ github.event.inputs.target || 'main' }}))
+#          tenant1-name: ${{ secrets.TENANT1_NAME }}
+#          tenant1-apitoken: ${{ secrets.TENANT1_APITOKEN }}
+#          tenant1-apitoken-nosettings: ${{ secrets.TENANT1_APITOKEN_NOSETTINGS }}
+#          tenant1-dataingesttoken: ${{ secrets.TENANT1_DATAINGESTTOKEN }}
+#          tenant1-oauth-client-id: ${{ secrets.TENANT1_OAUTH_CLIENT_ID }}
+#          tenant1-oauth-secret: ${{ secrets.TENANT1_OAUTH_SECRET }}
+#          tenant1-oauth-urn: ${{ secrets.TENANT1_OAUTH_URN }}
+#          tenant2-name: ${{ secrets.TENANT2_NAME }}
+#          tenant2-apitoken: ${{ secrets.TENANT2_APITOKEN }}
+#          tenant2-dataingesttoken: ${{ secrets.TENANT2_DATAINGESTTOKEN }}
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#      - name: Determine cluster status
+#        if: failure()
+#        run: |
+#          if [[ "${{ steps.run_e2e_test.outputs.cluster_status }}" == "skipped" ]]; then
+#            exit 1
+#          fi
 
   notify-slack:
     name: Notify test results in Slack
     environment: E2E
-    needs: [ "run-in-k8s", "run-in-ocp", "run-in-ocp-fips" ]
+    needs: [ "run-in-k8s"]
     runs-on: ubuntu-24.04
     if: ${{ always() }}
     steps:
@@ -141,6 +141,7 @@ jobs:
         env:
           TARGET_BRANCH: ${{ github.event.inputs.target || 'main' }}
         run: |
+          set -ex
           get_status() {
             if [ "$1" = "skipped" ]; then
               echo "cluster creation failed and skipped tests :large_yellow_circle:"
